# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# AppStore
KEY_FILE_PATH = "/Users/sameerkhan/Desktop/InstaCash\ Apps/p8\ key\ of\ InstaCash/AuthKey_DVM2UH7XLT.p8"
KEY_ID = "DVM2UH7XLT"
ISSUER_ID = "69a6de95-94e2-47e3-e053-5b8c7c11a4d1"
WORKSPACE_PATH = "InstaCashSDK.xcworkspace"
TARGET_SCHEME = "InstaCashSDK"
CONFIG_APPSTORE = "Release"
OUTPUT_DIRECTORY = "./fastlane/builds"

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :release do
    app_store_connect_api_key(
      key_id: KEY_ID,
      issuer_id: ISSUER_ID,
      key_filepath: KEY_FILE_PATH,
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    build_app(workspace: WORKSPACE_PATH,
              scheme: TARGET_SCHEME,
              configuration: CONFIG_APPSTORE,
              export_method: "app-store",
              export_options: {
                provisioningProfiles: {
                  "in.InstaSDK.InstaCashSDK" => "match AppStore in.InstaSDK.InstaCashSDK"
                }
              },
            )
    upload_to_testflight
  end
end
